apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: christiankreuzbergerdtx/go-mini-server
      docker:    # 	beta describes an artifact built from a Dockerfile.
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - deploy/deployment.yaml
