apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: go-mini-server
  name: go-mini-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: go-mini-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: go-mini-server
    spec:
      containers:
        - image: christiankreuzbergerdtx/go-mini-server:latest
          imagePullPolicy: IfNotPresent
          name: go-mini-server
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
# [START service]
apiVersion: v1
kind: Service
metadata:
  name: go-mini-server
  labels:
    run: go-mini-server
spec:
  type: LoadBalancer # note: use type loadbalancer if you want to expose it using a loadbalancer
  ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8080
  selector:
    run: go-mini-server
# [END service]